spring:
  application:
    name: royal-club-football
  datasource:
    url: jdbc:mysql://localhost:3306/royal_club_football?useSSL=false&serverTimezone=UTC
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true

server:
  port: 9191
