spring:
  application:
    name: royal-club-football

  main:
    allow-circular-references: true

  datasource:
    url: jdbc:mysql://localhost:3306/royal_club_football?useSSL=false&serverTimezone=UTC
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    time-zone: UTC  # Ensure Jackson operates with UTC for date serialization

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate  # Validate schema without altering it
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        jdbc.time_zone: UTC  # Ensures Hibernate operates in UTC

  flyway:
    baseline-on-migrate: true  # Ensure Flyway migrates from a clean baseline



server:
  port: 9191

jwt:
  secret: YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXoxMjM0NTY3ODkwYWJjZGVmZ2hpamts
  expiration: 604800000  # Token expiration in milliseconds (7 days)

logging:
  level:
    root: INFO  # Default log level for the entire application
    com.bjit.royalclub.royalclubfootball: INFO  # Specific log level for your application package
  file:
    name: logs/royal_club_football.log  # Log file name and location
  logback:
    rollingpolicy:
      file-name-pattern: logs/royal_club_football.%d{yyyy-MM-dd}.%i.gz.log  # Rolling file configuration
      max-file-size: 10MB
      total-size-cap: 1GB
      max-history: 7
      clean-history-on-start: true